language: objective-c
osx_image: xcode10.1
env:
  global:
  - IOS_SDK=iphonesimulator12.1
  - SCHEME=CustomLoader
  - WORKSPACE=CustomLoader.xcworkspace
  matrix:
    - DESTINATION="OS=12.0,name=iPhone 8" SDK="$IOS_SDK" POD_LINT="NO"
    - DESTINATION="OS=11.1,name=iPhone 8" SDK="$IOS_SDK" POD_LINT="NO"
    - DESTINATION="OS=10.1,name=iPhone 7" SDK="$IOS_SDK" POD_LINT="NO"
    - DESTINATION="OS=9.0,name=iPhone 6" SDK="$IOS_SDK" POD_LINT="YES"
script:
  # important make sure that xcodebuid exit code is passed to xcpretty
  - set -o pipefail
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test | xcpretty
  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi